### ISSUE TITLE
npm start does not start project

### ISSUE THREAD

**Issue by KrzysztofKominiak8** [GetDaStick/backendless-example#1]
After cloning I executed:
`npm install`,
then I was trying to start this project using:
`npm start`,
but without a victory result.
Printout is the following:

>  employee-front-end@1.0.0 start C:\Users\me\Desktop\backendless-example
> ng serve --proxy-config proxy.conf.js
>
>Cannot read property 'config' of null
>TypeError: Cannot read property 'config' of null
>    at Class.run (C:\Users\me\Desktop\backendless->example\node_modules\@angular\cli\tasks\serve.js:51:63)
    at check_port_1.checkPort.then.port (C:\Users\me\Desktop\backendless-example\node_modules\@angular\cli\commands\serve.js:121:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! employee-front-end@1.0.0 start: `ng serve --proxy-config proxy.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the employee-front-end@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2017-10-18T12_29_59_910Z-debug.log

Content of C:\Users\me\AppData\Roaming\npm-cache\_logs\2017-10-18T12_29_59_910Z-debug.log:

>0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.4.2
3 info using node@v6.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle employee-front-end@1.0.0~prestart: employee-front-end@1.0.0
6 info lifecycle employee-front-end@1.0.0~start: employee-front-end@1.0.0
7 verbose lifecycle employee-front-end@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle employee-front-end@1.0.0~start: PATH: ...
9 verbose lifecycle employee-front-end@1.0.0~start: CWD: C:\Users\me\Desktop\backendless-example
10 silly lifecycle employee-front-end@1.0.0~start: Args: [ '/d /s /c', 'ng serve --proxy-config proxy.conf.js' ]
11 silly lifecycle employee-front-end@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle employee-front-end@1.0.0~start: Failed to exec start script
13 verbose stack Error: employee-front-end@1.0.0 start: `ng serve --proxy-config proxy.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid employee-front-end@1.0.0
15 verbose cwd C:\Users\me\Desktop\backendless-example
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v6.11.4
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error employee-front-end@1.0.0 start: `ng serve --proxy-config proxy.conf.js`
22 error Exit status 1
23 error Failed at the employee-front-end@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

I do not know what is wrong.

**Comment by BarinDwalin** [comment]
Skipped .angular-cli.json
